# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
snapcrafts:
  -
    publish: true
    summary: obt is a downloader for the GitHub release page.
    description: obt is a downloader for the GitHub release page.
    license: MIT
    base: core18
    apps:
      drumroll:
        plugs: ["network"]
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
